# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-19 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rantest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
